# Generated by Django 5.1.7 on 2025-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamassignment',
            name='vote',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
