# Generated by Django 5.1.7 on 2025-04-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchteamassignment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchperformance',
            name='present',
        ),
    ]
