# Generated by Django 5.1.7 on 2025-04-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_delete_playerstats'),
        ('matches', '0003_remove_matchperformance_present'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchperformance',
            unique_together={('match', 'player', 'goals')},
        ),
    ]
