# Generated by Django 5.1.7 on 2025-04-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_matchperformance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callup',
            options={'verbose_name': 'Convocazione', 'verbose_name_plural': 'Convocazioni'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Partita', 'verbose_name_plural': 'Partite'},
        ),
        migrations.AlterModelOptions(
            name='matchconvocation',
            options={'verbose_name': 'Convocazione Giocatore', 'verbose_name_plural': 'Convocazioni Giocatori'},
        ),
        migrations.AlterModelOptions(
            name='matchperformance',
            options={'verbose_name': 'Prestazione Giocatore', 'verbose_name_plural': 'Prestazioni Giocatori'},
        ),
        migrations.AlterModelOptions(
            name='matchteamassignment',
            options={'verbose_name': 'Assegnazione Giocatore a Squadra', 'verbose_name_plural': 'Assegnazioni Giocatori a Squadra'},
        ),
    ]
