# Generated by Django 5.1.7 on 2025-04-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groupjoinrequest_options'),
        ('matches', '0005_alter_callup_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchperformance',
            unique_together={('match', 'player')},
        ),
        migrations.RemoveField(
            model_name='matchperformance',
            name='vote',
        ),
    ]
