# Generated by Django 5.1.7 on 2025-04-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_playervote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name': 'Statistiche Giocatore', 'verbose_name_plural': 'Statistiche Giocatori'},
        ),
    ]
