# Generated by Django 5.1.7 on 2025-04-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_playerstats_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playervote',
            options={'verbose_name': 'Voto Giocatore', 'verbose_name_plural': 'Voti Giocatori'},
        ),
    ]
