# Generated by Django 5.1.7 on 2025-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_playervote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='average_vote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
