# Generated by Django 5.1.7 on 2025-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_playerstats_average_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='mvp_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='top_scorer',
            field=models.BooleanField(default=False),
        ),
    ]
