# Generated by Django 5.1.7 on 2025-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_role',
            field=models.CharField(blank=True, help_text='Es. Portiere, Difensore, ecc.', max_length=50, verbose_name='Ruolo in campo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizzatore'), ('player', 'Giocatore')], default='player', max_length=20),
        ),
    ]
