# Generated by Django 5.1.7 on 2025-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_player_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_emails',
            field=models.BooleanField(default=True, verbose_name='Accetta email da PlayOn'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Accetta messaggi WhatsApp'),
        ),
    ]
