# Generated by Django 5.1.7 on 2025-04-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_playerstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
