# Generated by Django 5.1.7 on 2025-04-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_delete_playerstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupjoinrequest',
            options={'verbose_name': 'Richiesta di adesione al gruppo', 'verbose_name_plural': 'Richieste di adesione ai gruppi'},
        ),
    ]
