# Generated by Django 5.1.7 on 2025-05-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_player_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='groups.group'),
        ),
    ]
