# Generated by Django 5.1.7 on 2025-04-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_matchcomment_options_and_more'),
        ('notifications', '0003_alter_notification_options_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
    ]
